version: 2
jobs:
  build:
    docker:
      - image: docker:latest

    steps:
      - checkout

      - run:
          name: Build and push Docker image
          command: chmod +x ./build.sh && ./build.sh