version: 2
jobs:
  build:
    machine:
      pre:
        - curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0
        - pip install --upgrade pip
        - pip install docker-compose

      services:
        - docker

    dependencies:
      pre:
        - sudo pip install docker-compose

    # Adiciona uma seção para acionar a implantação quando todos os testes passarem
    deployment:
      # Adiciona subseção para instruir o circle ci a publicar no Docker Hub
      hub:
        # Configura as branches que devem acionar as instruções de implantação
        branch: [circle_ci_publish, master]
        # Especifica os comandos docker a serem executados
        commands:
          - docker push $DOCKER_HUB_USER_ID/dockerapp:latest