version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout

      - run:
          name: Docker Build
          command: chmod +x ./build.sh && ./build.sh

      - run:
          name: Docker Login
          command: docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD

      - run:
          name: Docker send image to hub
          command: |
            docker push jgcl88/php71databases:$CIRCLE_SHA1
            docker push jgcl88/php71databases:latest
