version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout

      - run:
          name: Docker Build
          command: chmod +x ./build.sh && ./build.sh

      - run:
          name: Docker Login
          command: docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD

      - run:
          name: Docker send image to hub
          command: |
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            docker build -t jgcl88/php71databases:$TAG .
            docker images
            docker push jgcl88/php71databases:$TAG
            docker tag jgcl88/php71databases:$TAG jgcl88/php71databases:latest
            docker push jgcl88/php71databases:latest
